CREATE TABLE [dbo].[PRODUCTO]
(
[CODPROD] [int] NOT NULL IDENTITY(1, 1),
[NOMPROD] [varchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CANTPROD] [int] NOT NULL,
[PRECPROD] [decimal] (10, 2) NOT NULL,
[CATPROD] [int] NOT NULL
) ON [PRIMARY]
GO
