CREATE TABLE [dbo].[CATEGORIA]
(
[CODCAT] [int] NOT NULL IDENTITY(1, 1),
[NOMCAT] [varchar] (100) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CATEGORIA] ADD CONSTRAINT [PK_CATEGORIA] PRIMARY KEY CLUSTERED  ([CODCAT]) ON [PRIMARY]
GO
